import { Session, SessionType, CoverageStatus, Priority, User, DateTab, Conference } from './types';

export const CONFERENCES: Conference[] = [
  {
    id: '1',
    title: 'ASCO Annual Meeting 2026',
    startDate: 'May 28, 2026',
    endDate: 'Jun 2, 2026',
    location: 'Chicago, IL, USA',
    attendees: '42,000 expected attendees',
    competitors: 5,
    priority: 'high',
    status: 'upcoming',
    therapeuticAreas: ['Lung Cancer', 'Breast Cancer', 'Melanoma', 'Immunotherapy']
  },
  {
    id: 'ongoing-1',
    title: 'WCLC 2026 - World Conference on Lung Cancer',
    startDate: 'Feb 7, 2026',
    endDate: 'Feb 10, 2026',
    location: 'Barcelona, Spain',
    attendees: '7,500 expected attendees',
    competitors: 3,
    priority: 'high',
    status: 'ongoing',
    therapeuticAreas: ['NSCLC', 'SCLC', 'Mesothelioma']
  },
  {
    id: '2',
    title: 'ACC Scientific Session 2026',
    startDate: 'Mar 14, 2026',
    endDate: 'Mar 16, 2026',
    location: 'Atlanta, GA, USA',
    attendees: '18,000 expected attendees',
    competitors: 4,
    priority: 'high',
    status: 'upcoming',
    therapeuticAreas: ['Heart Failure', 'Arrhythmia', 'Preventive Cardiology']
  },
  {
    id: '3',
    title: 'AAN Annual Meeting 2026',
    startDate: 'Apr 25, 2026',
    endDate: 'May 1, 2026',
    location: 'Seattle, WA, USA',
    attendees: '15,000 expected attendees',
    competitors: 4,
    priority: 'medium',
    status: 'upcoming',
    therapeuticAreas: ['Alzheimer\'s', 'Multiple Sclerosis', 'Parkinson\'s', 'Epilepsy']
  },
  {
    id: 'comp-1',
    title: 'ASH Annual Meeting 2025',
    startDate: 'Dec 6, 2025',
    endDate: 'Dec 9, 2025',
    location: 'New Orleans, LA, USA',
    attendees: '30,000 attendees',
    competitors: 6,
    priority: 'high',
    status: 'completed',
    therapeuticAreas: ['Hematology', 'Leukemia', 'Lymphoma']
  },
  {
    id: '4',
    title: 'EULAR European Congress 2026',
    startDate: 'Jun 10, 2026',
    endDate: 'Jun 13, 2026',
    location: 'Vienna, Austria',
    attendees: '14,000 expected attendees',
    competitors: 4,
    priority: 'high',
    status: 'upcoming',
    therapeuticAreas: ['Rheumatoid Arthritis', 'Lupus', 'Psoriatic Arthritis']
  },
  {
    id: 'up-1',
    title: 'ESMO Congress 2026',
    startDate: 'Sep 18, 2026',
    endDate: 'Sep 22, 2026',
    location: 'Paris, France',
    attendees: '25,000 expected attendees',
    competitors: 5,
    priority: 'high',
    status: 'upcoming',
    therapeuticAreas: ['Genitourinary Cancer', 'GI Cancer', 'Precision Medicine']
  },
  {
    id: 'ongoing-2',
    title: 'SITC Annual Meeting 2026',
    startDate: 'Feb 8, 2026',
    endDate: 'Feb 11, 2026',
    location: 'National Harbor, MD, USA',
    attendees: '5,000 expected attendees',
    competitors: 2,
    priority: 'medium',
    status: 'ongoing',
    therapeuticAreas: ['Immunotherapy', 'Tumor Immunology']
  },
  {
    id: 'comp-2',
    title: 'San Antonio Breast Cancer Symposium 2025',
    startDate: 'Dec 9, 2025',
    endDate: 'Dec 13, 2025',
    location: 'San Antonio, TX, USA',
    attendees: '10,000 attendees',
    competitors: 4,
    priority: 'high',
    status: 'completed',
    therapeuticAreas: ['Breast Cancer', 'HER2+', 'Triple Negative']
  }
];

export const USERS: User[] = [
  { id: '1', name: 'Mark Porter', role: 'Lead', avatar: 'https://picsum.photos/seed/mark/32/32' },
  { id: '2', name: 'Emma Liu', role: 'Analyst', avatar: 'https://picsum.photos/seed/emma/32/32' },
  { id: '3', name: 'Jacob Schmidt', role: 'Analyst', avatar: 'https://picsum.photos/seed/jacob/32/32' },
  { id: '4', name: 'Sarah Chen', role: 'Analyst', avatar: 'https://picsum.photos/seed/sarah/32/32' },
];

export const DATE_TABS: DateTab[] = [
  { label: 'May 28', date: '2026-05-28', isActive: false },
  { label: 'May 29', date: '2026-05-29', isActive: false },
  { label: 'May 30', date: '2026-05-30', isActive: false },
  { label: 'May 31', date: '2026-05-31', isActive: false },
  { label: 'Jun 1', date: '2026-06-01', isActive: false },
  { label: 'Jun 2', date: '2026-06-02', isActive: false },
];

export const SESSIONS: Session[] = [
  {
    id: 's1',
    title: 'Pre-Conference Workshop: Precision Oncology Basics',
    abstractId: 'PRE-01',
    date: '2026-05-28',
    startTime: '10:00 am',
    endTime: '12:00 pm',
    location: 'S105',
    track: 'General',
    type: SessionType.SYMPOSIUM,
    priority: Priority.MEDIUM,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[0]],
    matchScore: 88,
  },
  {
    id: 's2',
    title: 'ASCO 2026 Opening Session: Presidential Address & Karnofsky Lecture',
    abstractId: 'Opening',
    date: '2026-05-29',
    startTime: '9:30 am',
    endTime: '11:30 am',
    location: 'Hall B1',
    track: 'General',
    type: SessionType.SYMPOSIUM,
    priority: Priority.CRITICAL,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[0]],
    matchScore: 99,
  },
  {
    id: 's3',
    title: 'Precision Medicine in Gastrointestinal Cancers: Translating Science',
    abstractId: 'GI-01',
    date: '2026-05-30',
    startTime: '1:15 pm',
    endTime: '4:15 pm',
    location: 'Room S406',
    track: 'Gastrointestinal Cancer',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    matchScore: 85,
  },
  {
    id: 's4',
    title: 'Emerging Targeted Therapies in HER2-Low Metastatic Breast Cancer',
    abstractId: 'BC-202',
    date: '2026-05-31',
    startTime: '8:00 am',
    endTime: '9:30 am',
    location: 'Room E350',
    track: 'Breast Cancer',
    type: SessionType.SYMPOSIUM,
    priority: Priority.HIGH,
    status: CoverageStatus.COMPLETE,
    assignedTo: [USERS[2], USERS[3]],
    matchScore: 94,
  },
  {
    id: 's5',
    title: 'Immune Checkpoint Inhibitor Resistance in NSCLC: Novel Combinations',
    abstractId: 'LC-405',
    date: '2026-06-01',
    startTime: '3:00 pm',
    endTime: '4:30 pm',
    location: 'Room W190',
    track: 'Lung Cancer',
    type: SessionType.ORAL,
    priority: Priority.MEDIUM,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[1]],
    matchScore: 88,
  },
  {
    id: 's6',
    title: 'AI in Oncology: Enhancing Clinical Decision Support',
    abstractId: 'HIT-10',
    date: '2026-06-02',
    startTime: '10:10 am',
    endTime: '11:40 am',
    location: 'Electronic Poster Hall',
    track: 'Health IT',
    type: SessionType.POSTER,
    priority: Priority.MEDIUM,
    status: CoverageStatus.IN_PROGRESS,
    assignedTo: [USERS[1], USERS[3]],
    matchScore: 91,
  },
  {
    id: 's7',
    title: 'Developments in Targeted Alpha Therapy for Prostate Cancer',
    abstractId: 'GU-88',
    date: '2026-05-29',
    startTime: '8:00 am',
    endTime: '9:30 am',
    location: 'Room S100',
    track: 'Genitourinary Cancer',
    type: SessionType.ORAL,
    priority: Priority.CRITICAL,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[0], USERS[2]],
    matchScore: 97,
  }
];

export const AI_SUGGESTIONS = [
  {
    id: 'ai1',
    title: 'Precision Medicine in GI Cancers',
    reason: 'New Phase III data for KRAS-wildtype pancreatic cancer.',
    score: 98,
    type: 'High Relevance'
  },
  {
    id: 'ai2',
    title: 'HER2-Low Breast Cancer Updates',
    reason: 'Strategic deep-dive into novel ADCs (Antibody-Drug Conjugates).',
    score: 94,
    type: 'Critical Insight'
  },
  {
    id: 'ai3',
    title: 'Immune Checkpoint Resistance',
    reason: 'Co-therapy results for refractory NSCLC patients.',
    score: 89,
    type: 'Strategic'
  }
];