import { Session, SessionType, CoverageStatus, Priority, User, DateTab, Conference } from './types';

export const CONFERENCES: Conference[] = [
  // UPCOMING CONFERENCES (5)
  {
    id: '1',
    title: 'ASCO Annual Meeting 2026',
    startDate: 'May 29, 2026',
    endDate: 'Jun 2, 2026',
    location: 'Chicago, IL, USA',
    attendees: '42,000 expected attendees',
    competitors: 5,
    priority: 'high',
    status: 'upcoming',
    therapeuticAreas: ['Lung Cancer', 'Breast Cancer', 'Melanoma', 'Immunotherapy'],
    logo: '/logos/asco-annual.jpg'
  },
  {
    id: '2',
    title: 'ACC.26 Annual Scientific Session',
    startDate: 'Mar 28, 2026',
    endDate: 'Mar 30, 2026',
    location: 'New Orleans, LA, USA',
    attendees: '14,800 expected attendees',
    competitors: 4,
    priority: 'high',
    status: 'upcoming',
    therapeuticAreas: ['Cardiology', 'Heart Failure', 'Structural Heart', 'Arrhythmia'],
    logo: '/logos/acc-annual.jpg'
  },
  {
    id: '3',
    title: 'AACR Annual Meeting 2026',
    startDate: 'Apr 17, 2026',
    endDate: 'Apr 22, 2026',
    location: 'San Diego, CA, USA',
    attendees: '22,500 expected attendees',
    competitors: 5,
    priority: 'high',
    status: 'upcoming',
    therapeuticAreas: ['Cancer Research', 'Translational Medicine', 'Precision Oncology'],
    logo: '/logos/aacr-annual.jpg'
  },
  {
    id: '4',
    title: 'IASLC WCLC 2026 - World Conference on Lung Cancer',
    startDate: 'Sep 12, 2026',
    endDate: 'Sep 15, 2026',
    location: 'Seoul, South Korea',
    attendees: '7,200 expected attendees',
    competitors: 3,
    priority: 'high',
    status: 'upcoming',
    therapeuticAreas: ['NSCLC', 'SCLC', 'Immunotherapy', 'Oncology'],
    logo: '/logos/iaslc-wclc.jpg'
  },
  {
    id: '5',
    title: 'ESMO Congress 2026',
    startDate: 'Oct 23, 2026',
    endDate: 'Oct 27, 2026',
    location: 'Madrid, Spain',
    attendees: '25,000 expected attendees',
    competitors: 5,
    priority: 'high',
    status: 'upcoming',
    therapeuticAreas: ['Genitourinary Cancer', 'GI Cancer', 'Precision Medicine'],
    logo: '/logos/esmo-congress.jpg'
  },
  // ONGOING CONFERENCES (2)
  {
    id: 'ongoing-1',
    title: 'Advanced Therapies Week 2026',
    startDate: 'Feb 9, 2026',
    endDate: 'Feb 12, 2026',
    location: 'San Diego, CA, USA',
    attendees: '3,500 expected attendees',
    competitors: 2,
    priority: 'medium',
    status: 'ongoing',
    therapeuticAreas: ['Cell Therapy', 'Gene Therapy', 'Advanced Manufacturing'],
    logo: '/logos/advanced-therapies.jpg'
  },
  {
    id: 'ongoing-2',
    title: '17th Global Pharmacovigilance & Clinical Trials Summit',
    startDate: 'Feb 10, 2026',
    endDate: 'Feb 13, 2026',
    location: 'London, UK',
    attendees: '2,800 expected attendees',
    competitors: 2,
    priority: 'medium',
    status: 'ongoing',
    therapeuticAreas: ['Drug Safety', 'Clinical Trials', 'Regulatory Affairs'],
    logo: '/logos/pharmacovigilance.jpg'
  },
  // COMPLETED CONFERENCES (2)
  {
    id: 'comp-1',
    title: 'ASH Annual Meeting 2025',
    startDate: 'Dec 6, 2025',
    endDate: 'Dec 9, 2025',
    location: 'Orlando, FL, USA',
    attendees: '30,000 attendees',
    competitors: 6,
    priority: 'high',
    status: 'completed',
    therapeuticAreas: ['Hematology', 'Leukemia', 'Lymphoma', 'Cell Therapy'],
    logo: '/logos/ash-annual.jpg'
  },
  {
    id: 'comp-2',
    title: '44th J.P. Morgan Healthcare Conference',
    startDate: 'Jan 12, 2026',
    endDate: 'Jan 15, 2026',
    location: 'San Francisco, CA, USA',
    attendees: '10,000 attendees',
    competitors: 8,
    priority: 'high',
    status: 'completed',
    therapeuticAreas: ['Healthcare Investment', 'Pharma Strategy', 'Biotech Innovation'],
    logo: '/logos/jpm-healthcare.jpg'
  }
];

export const USERS: User[] = [
  { id: '1', name: 'Mark Porter', role: 'Lead', avatar: 'https://picsum.photos/seed/mark/32/32' },
  { id: '2', name: 'Emma Liu', role: 'Analyst', avatar: 'https://picsum.photos/seed/emma/32/32' },
  { id: '3', name: 'Jacob Schmidt', role: 'Analyst', avatar: 'https://picsum.photos/seed/jacob/32/32' },
  { id: '4', name: 'Sarah Chen', role: 'Analyst', avatar: 'https://picsum.photos/seed/sarah/32/32' },
];

export const DATE_TABS: DateTab[] = [
  { label: 'May 28', date: '2026-05-28', isActive: false },
  { label: 'May 29', date: '2026-05-29', isActive: false },
  { label: 'May 30', date: '2026-05-30', isActive: false },
  { label: 'May 31', date: '2026-05-31', isActive: false },
  { label: 'Jun 1', date: '2026-06-01', isActive: false },
  { label: 'Jun 2', date: '2026-06-02', isActive: false },
];

export const SESSIONS: Session[] = [
  // ASCO 2026 SESSIONS
  {
    id: 'asco-1',
    conferenceId: '1',
    title: 'ASCO 2026 Opening Session: Presidential Address & Karnofsky Lecture',
    abstractId: 'Opening',
    date: '2026-05-29',
    startTime: '9:30 am',
    endTime: '11:30 am',
    location: 'Hall B1',
    track: 'General',
    type: SessionType.SYMPOSIUM,
    priority: Priority.CRITICAL,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[0]],
    roomNo: 'B1',
    speakers: ['Dr. Lynn Schuchter (President)'],
    matchScore: 99,
  },
  {
    id: 'asco-2',
    conferenceId: '1',
    title: 'Precision Medicine in Gastrointestinal Cancers: Translating Science',
    abstractId: 'GI-01',
    date: '2026-05-30',
    startTime: '1:15 pm',
    endTime: '4:15 pm',
    location: 'Room S406',
    track: 'Gastrointestinal Cancer',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    roomNo: '406',
    speakers: ['Dr. Hans-Joachim Schmoll', 'Dr. Eileen O\'Reilly'],
    matchScore: 85,
  },
  {
    id: 'asco-3',
    conferenceId: '1',
    title: 'Emerging Targeted Therapies in HER2-Low Metastatic Breast Cancer',
    abstractId: 'BC-202',
    date: '2026-05-31',
    startTime: '8:00 am',
    endTime: '9:30 am',
    location: 'Room E350',
    track: 'Breast Cancer',
    type: SessionType.SYMPOSIUM,
    priority: Priority.HIGH,
    status: CoverageStatus.COMPLETE,
    assignedTo: [USERS[2], USERS[3]],
    roomNo: '350',
    speakers: ['Dr. Shanu Modi', 'Dr. Giuseppe Viale'],
    matchScore: 94,
  },
  {
    id: 'asco-4',
    conferenceId: '1',
    title: 'Immune Checkpoint Inhibitor Resistance in NSCLC: Novel Combinations',
    abstractId: 'LC-405',
    date: '2026-06-01',
    startTime: '3:00 pm',
    endTime: '4:30 pm',
    location: 'Room W190',
    track: 'Lung Cancer',
    type: SessionType.ORAL,
    priority: Priority.MEDIUM,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[1]],
    roomNo: '190',
    speakers: ['Dr. Alice Shaw', 'Dr. Lecia Sequist'],
    matchScore: 88,
  },
  {
    id: 'asco-5',
    conferenceId: '1',
    title: 'CAR-T Cell Therapy in Multiple Myeloma: Long-term Efficacy Data',
    abstractId: 'HM-112',
    date: '2026-05-30',
    startTime: '10:00 am',
    endTime: '11:30 am',
    location: 'Room S100',
    track: 'Hematologic Malignancies',
    type: SessionType.SYMPOSIUM,
    priority: Priority.HIGH,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    roomNo: '100',
    speakers: ['Dr. Nikhil Munshi', 'Dr. Paula Rodriguez-Otero'],
    matchScore: 91,
  },
  {
    id: 'asco-6',
    conferenceId: '1',
    title: 'Adjuvant Immunotherapy in Early-Stage Melanoma: New Standard of Care?',
    abstractId: 'MEL-301',
    date: '2026-05-31',
    startTime: '2:00 pm',
    endTime: '3:30 pm',
    location: 'Hall A',
    track: 'Melanoma',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[0]],
    roomNo: 'Main Hall',
    speakers: ['Dr. Georgina Long', 'Dr. Jeffrey Weber'],
    matchScore: 96,
  },
  {
    id: 'asco-7',
    conferenceId: '1',
    title: 'Circulating Tumor DNA as a Biomarker for Minimal Residual Disease',
    abstractId: 'GEN-504',
    date: '2026-06-01',
    startTime: '9:00 am',
    endTime: '10:30 am',
    location: 'Room E450',
    track: 'Precision Oncology',
    type: SessionType.ORAL,
    priority: Priority.MEDIUM,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    roomNo: '450',
    speakers: ['Dr. Maximilian Diehn', 'Dr. Aadel Chaudhuri'],
    matchScore: 78,
  },
  {
    id: 'asco-8',
    conferenceId: '1',
    title: 'Health Equity in Cancer Care: Addressing Disparities in Global Access',
    abstractId: 'HE-901',
    date: '2026-06-02',
    startTime: '11:00 am',
    endTime: '12:30 pm',
    location: 'Ballroom B',
    track: 'Health Services Research',
    type: SessionType.SYMPOSIUM,
    priority: Priority.MEDIUM,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    roomNo: 'Ballroom',
    speakers: ['Dr. Fumiko Chino', 'Dr. Robert Winn'],
    matchScore: 82,
  },

  // ACC.26 SESSIONS
  {
    id: 'acc-1',
    conferenceId: '2',
    title: 'Late-Breaking Clinical Trials: Women\'s Ischemia Trial to Reduce Events',
    abstractId: 'LBCT-01',
    date: '2026-03-28',
    startTime: '9:00 am',
    endTime: '10:30 am',
    location: 'Main Arena',
    track: 'Ischemic Heart Disease',
    type: SessionType.SYMPOSIUM,
    priority: Priority.CRITICAL,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    roomNo: 'Arena A',
    speakers: ['Dr. Janet Wei', 'Dr. C. Noel Bairey Merz'],
    matchScore: 92,
  },
  {
    id: 'acc-2',
    conferenceId: '2',
    title: 'Phase 3b STRIDE Trial: Subcutaneous Semaglutide in Peripheral Artery Disease',
    abstractId: 'CV-402',
    date: '2026-03-29',
    startTime: '1:30 pm',
    endTime: '3:00 pm',
    location: 'Hall C',
    track: 'Heart Failure',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[2]],
    roomNo: 'Room 202',
    speakers: ['Dr. Marc Bonaca', 'Dr. Mikhail Kosiborod'],
    matchScore: 89,
  },
  {
    id: 'acc-3',
    conferenceId: '2',
    title: 'RIVAWAR Trial: Rivaroxaban vs Warfarin in Acute LV Thrombus post-MI',
    abstractId: 'LBCT-05',
    date: '2026-03-30',
    startTime: '10:45 am',
    endTime: '12:15 pm',
    location: 'Auditorium B',
    track: 'Antithrombotic Therapy',
    type: SessionType.SYMPOSIUM,
    priority: Priority.HIGH,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    roomNo: 'Aud B',
    speakers: ['Dr. Ole Christian Mjølstad'],
    matchScore: 91,
  },

  // AACR 2026 SESSIONS
  {
    id: 'aacr-1',
    conferenceId: '3',
    title: 'Translational Cancer Research: From Bench to Bedside',
    abstractId: 'TR-101',
    date: '2026-04-18',
    startTime: '8:30 am',
    endTime: '10:00 am',
    location: 'Grand Ballroom',
    track: 'Translational Medicine',
    type: SessionType.SYMPOSIUM,
    priority: Priority.CRITICAL,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[0]],
    roomNo: 'GB-1',
    speakers: ['Dr. Tyler Jacks', 'Dr. Chi Van Dang'],
    matchScore: 96,
  },
  {
    id: 'aacr-2',
    conferenceId: '3',
    title: 'Novel Approaches to Targeting KRAS Mutations in Pancreatic Cancer',
    abstractId: 'PC-204',
    date: '2026-04-19',
    startTime: '2:00 pm',
    endTime: '3:30 pm',
    location: 'Room 6A',
    track: 'Precision Oncology',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[1]],
    roomNo: '6A',
    speakers: ['Dr. Andrew Aguirre', 'Dr. Alec Kimmelman'],
    matchScore: 93,
  },
  {
    id: 'aacr-3',
    conferenceId: '3',
    title: 'CAR-T Cell Therapy: Overcoming Solid Tumor Barriers',
    abstractId: 'IT-308',
    date: '2026-04-21',
    startTime: '11:00 am',
    endTime: '12:30 pm',
    location: 'Room 5B',
    track: 'Immunotherapy',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    roomNo: '5B',
    speakers: ['Dr. Carl June', 'Dr. Michel Sadelain'],
    matchScore: 95,
  },

  // WCLC 2026 SESSIONS
  {
    id: 'wclc-1',
    conferenceId: '4',
    title: 'MARIPOSA Study: Amivantamab plus Lazertinib in untreated EGFR-mutated NSCLC',
    abstractId: 'PL01.03',
    date: '2026-09-13',
    startTime: '10:00 am',
    endTime: '11:30 am',
    location: 'Auditorium 1',
    track: 'Targeted Therapy',
    type: SessionType.ORAL,
    priority: Priority.CRITICAL,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    roomNo: 'A1',
    speakers: ['Dr. Byoung Chul Cho'],
    matchScore: 96,
  },
  {
    id: 'wclc-2',
    conferenceId: '4',
    title: 'HARMONi-2: Ivonescimab versus Pembrolizumab in PD-L1+ Advanced NSCLC',
    abstractId: 'OA04.05',
    date: '2026-09-14',
    startTime: '2:15 pm',
    endTime: '3:45 pm',
    location: 'Room 301',
    track: 'Immunotherapy',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[3]],
    roomNo: '301',
    speakers: ['Dr. Caicun Zhou'],
    matchScore: 94,
  },
  {
    id: 'wclc-3',
    conferenceId: '4',
    title: 'CheckMate 77T vs 816: Perioperative vs Neoadjuvant Nivolumab for Resectable NSCLC',
    abstractId: 'PL02.04',
    date: '2026-09-13',
    startTime: '3:00 pm',
    endTime: '4:30 pm',
    location: 'Auditorium 1',
    track: 'Immunotherapy',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[1]],
    roomNo: 'A1',
    speakers: ['Dr. Tina Cascone'],
    matchScore: 93,
  },

  // ESMO 2026 SESSIONS
  {
    id: 'esmo-1',
    conferenceId: '5',
    title: 'Presidential Symposium: Breakthroughs in Precision Medicine',
    abstractId: 'PS-001',
    date: '2026-10-24',
    startTime: '9:00 am',
    endTime: '10:30 am',
    location: 'Main Hall',
    track: 'Precision Medicine',
    type: SessionType.SYMPOSIUM,
    priority: Priority.CRITICAL,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    roomNo: 'MH-1',
    speakers: ['Dr. Fabrice André', 'Dr. Josep Tabernero'],
    matchScore: 98,
  },
  {
    id: 'esmo-2',
    conferenceId: '5',
    title: 'Novel Antibody-Drug Conjugates in Genitourinary Cancers',
    abstractId: 'GU-205',
    date: '2026-10-25',
    startTime: '2:00 pm',
    endTime: '3:30 pm',
    location: 'Room 7',
    track: 'Genitourinary Cancer',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[2]],
    roomNo: 'R7',
    speakers: ['Dr. Joaquim Bellmunt', 'Dr. Petros Grivas'],
    matchScore: 90,
  },
  {
    id: 'esmo-3',
    conferenceId: '5',
    title: 'Immunotherapy Combinations in Advanced Gastric Cancer',
    abstractId: 'GI-308',
    date: '2026-10-26',
    startTime: '11:15 am',
    endTime: '12:45 pm',
    location: 'Room 4',
    track: 'GI Cancer',
    type: SessionType.ORAL,
    priority: Priority.MEDIUM,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[1]],
    roomNo: 'R4',
    speakers: ['Dr. Yung-Jue Bang', 'Dr. Kohei Shitara'],
    matchScore: 87,
  },

  // ADVANCED THERAPIES WEEK 2026 SESSIONS (ONGOING)
  {
    id: 'atw-1',
    conferenceId: 'ongoing-1',
    title: 'Gene Therapy Manufacturing: Scaling for Commercial Success',
    abstractId: 'MFG-101',
    date: '2026-02-10',
    startTime: '9:00 am',
    endTime: '10:30 am',
    location: 'Convention Center Hall A',
    track: 'Advanced Manufacturing',
    type: SessionType.SYMPOSIUM,
    priority: Priority.HIGH,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[0]],
    roomNo: 'Hall A',
    speakers: ['Dr. Paula Loria', 'Dr. Steven Nichtberger'],
    matchScore: 88,
  },
  {
    id: 'atw-2',
    conferenceId: 'ongoing-1',
    title: 'CAR-T Cell Therapy: Next Generation Engineering Strategies',
    abstractId: 'CT-204',
    date: '2026-02-11',
    startTime: '1:30 pm',
    endTime: '3:00 pm',
    location: 'Room 3B',
    track: 'Cell Therapy',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[1]],
    roomNo: '3B',
    speakers: ['Dr. Renier Brentjens', 'Dr. Crystal Mackall'],
    matchScore: 92,
  },

  // PHARMACOVIGILANCE SUMMIT 2026 SESSIONS (ONGOING)
  {
    id: 'pv-1',
    conferenceId: 'ongoing-2',
    title: 'AI and Machine Learning in Pharmacovigilance Signal Detection',
    abstractId: 'PV-102',
    date: '2026-02-11',
    startTime: '10:00 am',
    endTime: '11:30 am',
    location: 'Conference Hall 1',
    track: 'Drug Safety',
    type: SessionType.SYMPOSIUM,
    priority: Priority.MEDIUM,
    status: CoverageStatus.ASSIGNED,
    assignedTo: [USERS[2]],
    roomNo: 'CH-1',
    speakers: ['Dr. Mira Ilic', 'Dr. Andrew Bate'],
    matchScore: 85,
  },
  {
    id: 'pv-2',
    conferenceId: 'ongoing-2',
    title: 'Regulatory Harmonization: Global Pharmacovigilance Standards',
    abstractId: 'REG-205',
    date: '2026-02-12',
    startTime: '2:00 pm',
    endTime: '3:30 pm',
    location: 'Room B2',
    track: 'Regulatory Affairs',
    type: SessionType.ORAL,
    priority: Priority.MEDIUM,
    status: CoverageStatus.UNASSIGNED,
    assignedTo: [],
    roomNo: 'B2',
    speakers: ['Dr. Peter Arlett', 'Dr. Gerald Dal Pan'],
    matchScore: 82,
  },

  // ASH 2025 SESSIONS (COMPLETED)
  {
    id: 'ash-1',
    conferenceId: 'comp-1',
    title: 'Plenary Session: Advances in CAR-T for Multiple Myeloma',
    abstractId: 'PL-001',
    date: '2025-12-07',
    startTime: '8:00 am',
    endTime: '9:30 am',
    location: 'Grand Ballroom',
    track: 'Cell Therapy',
    type: SessionType.SYMPOSIUM,
    priority: Priority.CRITICAL,
    status: CoverageStatus.COMPLETE,
    assignedTo: [USERS[0], USERS[1]],
    roomNo: 'GB',
    speakers: ['Dr. Nikhil Munshi', 'Dr. Jesus San-Miguel'],
    matchScore: 97,
  },
  {
    id: 'ash-2',
    conferenceId: 'comp-1',
    title: 'Novel Therapies in Acute Myeloid Leukemia',
    abstractId: 'AML-304',
    date: '2025-12-08',
    startTime: '1:00 pm',
    endTime: '2:30 pm',
    location: 'Room 210',
    track: 'Leukemia',
    type: SessionType.ORAL,
    priority: Priority.HIGH,
    status: CoverageStatus.COMPLETE,
    assignedTo: [USERS[2]],
    roomNo: '210',
    speakers: ['Dr. Elihu Estey', 'Dr. Courtney DiNardo'],
    matchScore: 94,
  },

  // J.P. MORGAN 2026 SESSIONS (COMPLETED)
  {
    id: 'jpm-1',
    conferenceId: 'comp-2',
    title: 'Keynote: The Future of Precision Medicine and AI in Drug Discovery',
    abstractId: 'KEY-001',
    date: '2026-01-13',
    startTime: '9:00 am',
    endTime: '10:00 am',
    location: 'Westin St. Francis Grand Ballroom',
    track: 'Pharma Strategy',
    type: SessionType.SYMPOSIUM,
    priority: Priority.CRITICAL,
    status: CoverageStatus.COMPLETE,
    assignedTo: [USERS[0]],
    roomNo: 'GB',
    speakers: ['Dr. Paul Hudson (Sanofi CEO)', 'Dr. Emma Walmsley (GSK CEO)'],
    matchScore: 99,
  },
  {
    id: 'jpm-2',
    conferenceId: 'comp-2',
    title: 'Biotech Innovation Panel: Gene Editing and Cell Therapy Breakthroughs',
    abstractId: 'BIO-205',
    date: '2026-01-14',
    startTime: '2:00 pm',
    endTime: '3:30 pm',
    location: 'Marriott Marquis Salon',
    track: 'Biotech Innovation',
    type: SessionType.SYMPOSIUM,
    priority: Priority.HIGH,
    status: CoverageStatus.COMPLETE,
    assignedTo: [USERS[1], USERS[3]],
    roomNo: 'Salon A',
    speakers: ['Dr. Jennifer Doudna', 'Dr. Derrick Rossi'],
    matchScore: 96,
  }
];

export const AI_SUGGESTIONS = [
  {
    id: 'ai1',
    title: 'Precision Medicine in GI Cancers',
    reason: 'New Phase III data for KRAS-wildtype pancreatic cancer.',
    score: 98,
    type: 'High Relevance'
  },
  {
    id: 'ai2',
    title: 'HER2-Low Breast Cancer Updates',
    reason: 'Strategic deep-dive into novel ADCs (Antibody-Drug Conjugates).',
    score: 94,
    type: 'Critical Insight'
  },
  {
    id: 'ai3',
    title: 'Immune Checkpoint Resistance',
    reason: 'Co-therapy results for refractory NSCLC patients.',
    score: 89,
    type: 'Strategic'
  }
];